name: build

on: [push]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
      - name: Configure
        run: mkdir build && cd build && cmake ..
      - name: Build
        run: cmake --build build
